// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xunite.h"

extern XUnite_Config XUnite_ConfigTable[];

XUnite_Config *XUnite_LookupConfig(u16 DeviceId) {
	XUnite_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XUNITE_NUM_INSTANCES; Index++) {
		if (XUnite_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XUnite_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XUnite_Initialize(XUnite *InstancePtr, u16 DeviceId) {
	XUnite_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XUnite_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XUnite_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

