// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rg_data_V
//        bit 31~0 - rg_data_V[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of g_data_V
//        bit 31~0 - g_data_V[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of out_data_V
//        bit 31~0 - out_data_V[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of adjs_data_V
//        bit 31~0 - adjs_data_V[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XG_RG_T_AXILITES_ADDR_RG_DATA_V_DATA   0x10
#define XG_RG_T_AXILITES_BITS_RG_DATA_V_DATA   32
#define XG_RG_T_AXILITES_ADDR_G_DATA_V_DATA    0x18
#define XG_RG_T_AXILITES_BITS_G_DATA_V_DATA    32
#define XG_RG_T_AXILITES_ADDR_OUT_DATA_V_DATA  0x20
#define XG_RG_T_AXILITES_BITS_OUT_DATA_V_DATA  32
#define XG_RG_T_AXILITES_ADDR_ADJS_DATA_V_DATA 0x28
#define XG_RG_T_AXILITES_BITS_ADJS_DATA_V_DATA 32

// control
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of N
//        bit 31~0 - N[31:0] (Read/Write)
// 0x14 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XG_RG_T_CONTROL_ADDR_N_DATA 0x10
#define XG_RG_T_CONTROL_BITS_N_DATA 32

