// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xg_rg_t.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XG_rg_t_CfgInitialize(XG_rg_t *InstancePtr, XG_rg_t_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XG_rg_t_Set_rg_data_V(XG_rg_t *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XG_rg_t_WriteReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_RG_DATA_V_DATA, Data);
}

u32 XG_rg_t_Get_rg_data_V(XG_rg_t *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XG_rg_t_ReadReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_RG_DATA_V_DATA);
    return Data;
}

void XG_rg_t_Set_g_data_V(XG_rg_t *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XG_rg_t_WriteReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_G_DATA_V_DATA, Data);
}

u32 XG_rg_t_Get_g_data_V(XG_rg_t *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XG_rg_t_ReadReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_G_DATA_V_DATA);
    return Data;
}

void XG_rg_t_Set_out_data_V(XG_rg_t *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XG_rg_t_WriteReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_OUT_DATA_V_DATA, Data);
}

u32 XG_rg_t_Get_out_data_V(XG_rg_t *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XG_rg_t_ReadReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_OUT_DATA_V_DATA);
    return Data;
}

void XG_rg_t_Set_adjs_data_V(XG_rg_t *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XG_rg_t_WriteReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_ADJS_DATA_V_DATA, Data);
}

u32 XG_rg_t_Get_adjs_data_V(XG_rg_t *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XG_rg_t_ReadReg(InstancePtr->Axilites_BaseAddress, XG_RG_T_AXILITES_ADDR_ADJS_DATA_V_DATA);
    return Data;
}

void XG_rg_t_Set_N(XG_rg_t *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XG_rg_t_WriteReg(InstancePtr->Control_BaseAddress, XG_RG_T_CONTROL_ADDR_N_DATA, Data);
}

u32 XG_rg_t_Get_N(XG_rg_t *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XG_rg_t_ReadReg(InstancePtr->Control_BaseAddress, XG_RG_T_CONTROL_ADDR_N_DATA);
    return Data;
}

