// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XG_RG_T_H
#define XG_RG_T_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xg_rg_t_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
    u32 Control_BaseAddress;
} XG_rg_t_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 Control_BaseAddress;
    u32 IsReady;
} XG_rg_t;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XG_rg_t_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XG_rg_t_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XG_rg_t_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XG_rg_t_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XG_rg_t_Initialize(XG_rg_t *InstancePtr, u16 DeviceId);
XG_rg_t_Config* XG_rg_t_LookupConfig(u16 DeviceId);
int XG_rg_t_CfgInitialize(XG_rg_t *InstancePtr, XG_rg_t_Config *ConfigPtr);
#else
int XG_rg_t_Initialize(XG_rg_t *InstancePtr, const char* InstanceName);
int XG_rg_t_Release(XG_rg_t *InstancePtr);
#endif


void XG_rg_t_Set_rg_data_V(XG_rg_t *InstancePtr, u32 Data);
u32 XG_rg_t_Get_rg_data_V(XG_rg_t *InstancePtr);
void XG_rg_t_Set_g_data_V(XG_rg_t *InstancePtr, u32 Data);
u32 XG_rg_t_Get_g_data_V(XG_rg_t *InstancePtr);
void XG_rg_t_Set_out_data_V(XG_rg_t *InstancePtr, u32 Data);
u32 XG_rg_t_Get_out_data_V(XG_rg_t *InstancePtr);
void XG_rg_t_Set_adjs_data_V(XG_rg_t *InstancePtr, u32 Data);
u32 XG_rg_t_Get_adjs_data_V(XG_rg_t *InstancePtr);
void XG_rg_t_Set_N(XG_rg_t *InstancePtr, u32 Data);
u32 XG_rg_t_Get_N(XG_rg_t *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
