// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xg_rg_t.h"

extern XG_rg_t_Config XG_rg_t_ConfigTable[];

XG_rg_t_Config *XG_rg_t_LookupConfig(u16 DeviceId) {
	XG_rg_t_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XG_RG_T_NUM_INSTANCES; Index++) {
		if (XG_rg_t_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XG_rg_t_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XG_rg_t_Initialize(XG_rg_t *InstancePtr, u16 DeviceId) {
	XG_rg_t_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XG_rg_t_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XG_rg_t_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

