// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xintersect.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XIntersect_CfgInitialize(XIntersect *InstancePtr, XIntersect_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XIntersect_Set_adj1_data_V(XIntersect *InstancePtr, XIntersect_Adj1_data_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 0, Data.word_0);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 4, Data.word_1);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 8, Data.word_2);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 12, Data.word_3);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 16, Data.word_4);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 20, Data.word_5);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 24, Data.word_6);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 28, Data.word_7);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 32, Data.word_8);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 36, Data.word_9);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 40, Data.word_10);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 44, Data.word_11);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 48, Data.word_12);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 52, Data.word_13);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 56, Data.word_14);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 60, Data.word_15);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 64, Data.word_16);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 68, Data.word_17);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 72, Data.word_18);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 76, Data.word_19);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 80, Data.word_20);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 84, Data.word_21);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 88, Data.word_22);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 92, Data.word_23);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 96, Data.word_24);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 100, Data.word_25);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 104, Data.word_26);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 108, Data.word_27);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 112, Data.word_28);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 116, Data.word_29);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 120, Data.word_30);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 124, Data.word_31);
}

XIntersect_Adj1_data_v XIntersect_Get_adj1_data_V(XIntersect *InstancePtr) {
    XIntersect_Adj1_data_v Data;

    Data.word_0 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 0);
    Data.word_1 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 4);
    Data.word_2 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 8);
    Data.word_3 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 12);
    Data.word_4 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 16);
    Data.word_5 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 20);
    Data.word_6 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 24);
    Data.word_7 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 28);
    Data.word_8 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 32);
    Data.word_9 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 36);
    Data.word_10 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 40);
    Data.word_11 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 44);
    Data.word_12 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 48);
    Data.word_13 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 52);
    Data.word_14 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 56);
    Data.word_15 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 60);
    Data.word_16 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 64);
    Data.word_17 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 68);
    Data.word_18 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 72);
    Data.word_19 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 76);
    Data.word_20 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 80);
    Data.word_21 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 84);
    Data.word_22 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 88);
    Data.word_23 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 92);
    Data.word_24 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 96);
    Data.word_25 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 100);
    Data.word_26 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 104);
    Data.word_27 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 108);
    Data.word_28 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 112);
    Data.word_29 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 116);
    Data.word_30 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 120);
    Data.word_31 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ1_DATA_V_DATA + 124);
    return Data;
}

void XIntersect_Set_adj2_data_V(XIntersect *InstancePtr, XIntersect_Adj2_data_v Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 0, Data.word_0);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 4, Data.word_1);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 8, Data.word_2);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 12, Data.word_3);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 16, Data.word_4);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 20, Data.word_5);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 24, Data.word_6);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 28, Data.word_7);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 32, Data.word_8);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 36, Data.word_9);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 40, Data.word_10);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 44, Data.word_11);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 48, Data.word_12);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 52, Data.word_13);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 56, Data.word_14);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 60, Data.word_15);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 64, Data.word_16);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 68, Data.word_17);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 72, Data.word_18);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 76, Data.word_19);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 80, Data.word_20);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 84, Data.word_21);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 88, Data.word_22);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 92, Data.word_23);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 96, Data.word_24);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 100, Data.word_25);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 104, Data.word_26);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 108, Data.word_27);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 112, Data.word_28);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 116, Data.word_29);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 120, Data.word_30);
    XIntersect_WriteReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 124, Data.word_31);
}

XIntersect_Adj2_data_v XIntersect_Get_adj2_data_V(XIntersect *InstancePtr) {
    XIntersect_Adj2_data_v Data;

    Data.word_0 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 0);
    Data.word_1 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 4);
    Data.word_2 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 8);
    Data.word_3 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 12);
    Data.word_4 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 16);
    Data.word_5 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 20);
    Data.word_6 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 24);
    Data.word_7 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 28);
    Data.word_8 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 32);
    Data.word_9 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 36);
    Data.word_10 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 40);
    Data.word_11 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 44);
    Data.word_12 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 48);
    Data.word_13 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 52);
    Data.word_14 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 56);
    Data.word_15 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 60);
    Data.word_16 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 64);
    Data.word_17 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 68);
    Data.word_18 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 72);
    Data.word_19 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 76);
    Data.word_20 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 80);
    Data.word_21 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 84);
    Data.word_22 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 88);
    Data.word_23 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 92);
    Data.word_24 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 96);
    Data.word_25 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 100);
    Data.word_26 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 104);
    Data.word_27 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 108);
    Data.word_28 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 112);
    Data.word_29 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 116);
    Data.word_30 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 120);
    Data.word_31 = XIntersect_ReadReg(InstancePtr->Control_BaseAddress, XINTERSECT_CONTROL_ADDR_ADJ2_DATA_V_DATA + 124);
    return Data;
}

